version: '3'

networks: 
  laravel: 

services:   
  nginx: 
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8088:80"
    volumes: 
      - ./src:/var/www/html  
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - mysql_service
      - php   
    networks: 
      - laravel


  mysql_service: 
    image: mysql:latest
    container_name: laravel_mysql
    restart: always
    tty: true
    ports: 
      - "4036:85"
    volumes: 
      - ./databse:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: laraveltest 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - laravel

  php:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html  
    ports: 
      - "9000:9000"  
    networks: 
      - laravel  